version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb_container

  mongodb_container:
    # This image automatically creates a replica set required for transactions
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tap
      MONGO_INITDB_ROOT_PASSWORD: tap
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
    # Make sure log colors show up correctly
    tty: true
