[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.20'
bytecode_hash = "none"
cbor_metadata = false


[rpc_endpoints]
optimism_goerli = "${OPTIMISM_GOERLI_RPC_URL}"
base_goerli = "${BASE_GOERLI_RPC_URL}"
local = "${LOCAL_RPC_URL}"

[etherscan]
optimism_goerli_etherscan = { key = "${ETHERSCAN_OPTIMISM_API_KEY}", chain = "goerli" }



# See more config options https://github.com/foundry-rs/foundry/tree/master/config
