name: Deploy on PR Merge to Demo

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute SSH Command
      env:
        PRIVATE_KEY: ${{ secrets.POETVM_SSH_PRIVATE_KEY}}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key poet@172.178.105.49 'cd /home/poet/tap-cap-table && git pull origin staging'
        rm -f private_key


